export enum GameEvent {
  GAME_STATE_CHANGED = "GAME_STATE_CHANGED",
  HARVEST = "HARVEST",
  PLANT = "PLANT",
  WATER = "WATER",
  PURCHASE_SEED = "PURCHASE_SEED",
  REFILL_WATER = "REFILL_WATER",
}
