export enum Intent {
  EQUIP_HARVESTING_TOOL = "EQUIP_HARVESTING_TOOL",
  EQUIP_PLANTING_TOOL = "EQUIP_PLANTING_TOOL",
  EQUIP_WATERING_TOOL = "EQUIP_WATERING_TOOL",
  HARVEST = "HARVEST",
  PLANT = "PLANT",
  WATER = "WATER",
  PURCHASE_SEED = "PURCHASE_SEED",
  REFILL_WATER = "REFILL_WATER",
}
